name: Implantación Automática

on:
  push:
    branches: [main]


jobs:
        deploy:
          runs-on: ubuntu-latest
      
          steps:
            - name: Checkout
              uses: actions/checkout@v2
      
            - name: Deploy
              run: |
                git clone https://github.com/sbc-juanarevalo/sbc_pruebas_terraform_aws.git
                
      