name: Implantación Automática

on:
  push:
    branches:
      - main


      jobs:
        deploy:
          runs-on: ubuntu-latest
      
          steps:
            - name: Checkout
              uses: actions/checkout@v2
      
            - name: Deploy
              run: |
                echo Aquí se colocan los comandos necesarios para implantar el código en la rama objetivo
      