name: Implantación Automática

on:
  push:
    branches: [main]


jobs:
        deploy:
          runs-on: ubuntu-latest
      
          steps:
            - name: Checkout
              uses: actions/checkout@v2
      
            - name: Deploy
              run: |
                git --version
                git clone https://github.com/sbc-juanarevalo/sbc_pruebas_terraform_aws.git
                cd sbc_pruebas_terraform_aws/src                
                cat main.tf
                

            - name:
              run: |
                terraform init
                ls
                cat README.md
                
                
      